imports:
    - { resource: parameters.yml }

services:
    app.product_repository:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.default_entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\Product
            
    app.purchase_repository:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.default_entity_manager:getRepository'
        arguments:
            - AppBundle\Entity\Purchase
    
    app.abstract_repository_manager:
        abstract: true
        arguments: 
            - '@doctrine.orm.default_entity_manager'
            - Doctrine\ORM\EntityRepository
    
    app.purchase_repository_manager:
        class: AppBundle\Repository\Managers\PurchaseRepositoryManager
        parent: app.abstract_repository_manager
        arguments: 
            index_1: '@app.purchase_repository'
        
    app.product_repository_manager:
        class: AppBundle\Repository\Managers\ProductRepositoryManager
        parent: app.abstract_repository_manager
        arguments:
            index_1: '@app.product_repository'
        
    app.cart_manager:
        class: AppBundle\Managers\CartManager
        arguments: [ '@session' ]
        
    app.purchase_manager:
        class: AppBundle\Managers\PurchaseManager
        arguments: [ '@app.purchase_repository_manager' ]
        
    app.product_manager:
        class: AppBundle\Managers\ProductManager
        arguments: [ '@app.product_repository_manager' ]
        
    app.paginator:
        class: AppBundle\Paginator\Paginator
        arguments: [ '@knp_paginator', '@request_stack' ]
        
    app.form_handler:
        class: AppBundle\Form\Handler\FormHandler
        arguments: [ '@form.factory', '@doctrine.orm.default_entity_manager' ]