services:
    app.product_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Product
    
    app.product_manager:
        class: AppBundle\Managers\ProductManager
        arguments: [ '@app.product_repository']
        
    app.cart_manager:
        class: AppBundle\Managers\CartManager
        
    app.paginator:
        class: AppBundle\Paginator\Paginator
        arguments: [ '@knp_paginator', '@request_stack' ]